language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by this project
    - build-tools-25.0.2

    # The SDK version used to compile this project
    - android-25
